package model;
// Generated Sep 6, 2018 2:41:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pass generated by hbm2java
 */
public class Pass  implements java.io.Serializable {


     private Integer passId;
     private Route route;
     private User user;
     private String issueAdte;
     private String validTill;
     private Set payments = new HashSet(0);
     private Set renewalRequests = new HashSet(0);

    public Pass() {
    }

    public Pass(Route route, User user, String issueAdte, String validTill, Set payments, Set renewalRequests) {
       this.route = route;
       this.user = user;
       this.issueAdte = issueAdte;
       this.validTill = validTill;
       this.payments = payments;
       this.renewalRequests = renewalRequests;
    }
   
    public Integer getPassId() {
        return this.passId;
    }
    
    public void setPassId(Integer passId) {
        this.passId = passId;
    }
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getIssueAdte() {
        return this.issueAdte;
    }
    
    public void setIssueAdte(String issueAdte) {
        this.issueAdte = issueAdte;
    }
    public String getValidTill() {
        return this.validTill;
    }
    
    public void setValidTill(String validTill) {
        this.validTill = validTill;
    }
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }
    public Set getRenewalRequests() {
        return this.renewalRequests;
    }
    
    public void setRenewalRequests(Set renewalRequests) {
        this.renewalRequests = renewalRequests;
    }




}


