package model;
// Generated Sep 6, 2018 2:41:38 PM by Hibernate Tools 4.3.1



/**
 * RenewalRequest generated by hbm2java
 */
public class RenewalRequest  implements java.io.Serializable {


     private Integer renewalRequest;
     private Pass pass;
     private String expiryOn;
     private String status;

    public RenewalRequest() {
    }

    public RenewalRequest(Pass pass, String expiryOn, String status) {
       this.pass = pass;
       this.expiryOn = expiryOn;
       this.status = status;
    }
   
    public Integer getRenewalRequest() {
        return this.renewalRequest;
    }
    
    public void setRenewalRequest(Integer renewalRequest) {
        this.renewalRequest = renewalRequest;
    }
    public Pass getPass() {
        return this.pass;
    }
    
    public void setPass(Pass pass) {
        this.pass = pass;
    }
    public String getExpiryOn() {
        return this.expiryOn;
    }
    
    public void setExpiryOn(String expiryOn) {
        this.expiryOn = expiryOn;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


