package model;
// Generated Sep 6, 2018 2:41:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Route generated by hbm2java
 */
public class Route  implements java.io.Serializable {


     private Integer routeId;
     private String routeName;
     private String startPlace;
     private String endingPlace;
     private String otherDetails;
     private Set passes = new HashSet(0);
     private Set buses = new HashSet(0);

    public Route() {
    }

	
    public Route(String routeName, String startPlace, String endingPlace, String otherDetails) {
        this.routeName = routeName;
        this.startPlace = startPlace;
        this.endingPlace = endingPlace;
        this.otherDetails = otherDetails;
    }
    public Route(String routeName, String startPlace, String endingPlace, String otherDetails, Set passes, Set buses) {
       this.routeName = routeName;
       this.startPlace = startPlace;
       this.endingPlace = endingPlace;
       this.otherDetails = otherDetails;
       this.passes = passes;
       this.buses = buses;
    }
   
    public Integer getRouteId() {
        return this.routeId;
    }
    
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }
    public String getRouteName() {
        return this.routeName;
    }
    
    public void setRouteName(String routeName) {
        this.routeName = routeName;
    }
    public String getStartPlace() {
        return this.startPlace;
    }
    
    public void setStartPlace(String startPlace) {
        this.startPlace = startPlace;
    }
    public String getEndingPlace() {
        return this.endingPlace;
    }
    
    public void setEndingPlace(String endingPlace) {
        this.endingPlace = endingPlace;
    }
    public String getOtherDetails() {
        return this.otherDetails;
    }
    
    public void setOtherDetails(String otherDetails) {
        this.otherDetails = otherDetails;
    }
    public Set getPasses() {
        return this.passes;
    }
    
    public void setPasses(Set passes) {
        this.passes = passes;
    }
    public Set getBuses() {
        return this.buses;
    }
    
    public void setBuses(Set buses) {
        this.buses = buses;
    }




}


