package model;
// Generated Sep 6, 2018 2:41:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String firstName;
     private String lastName;
     private String course;
     private String batch;
     private String gender;
     private String dob;
     private String houseName;
     private String place;
     private String pincode;
     private String phone;
     private String email;
     private String parentName;
     private String parentPhone;
     private Set passes = new HashSet(0);
     private Set newPassengerRequests = new HashSet(0);
     private Set payments = new HashSet(0);
     private Set feedbacks = new HashSet(0);
     private Set logins = new HashSet(0);

    public User() {
    }

	
    public User(String firstName, String lastName, String course, String batch, String gender, String dob, String houseName, String place, String pincode, String phone, String email, String parentName, String parentPhone) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.course = course;
        this.batch = batch;
        this.gender = gender;
        this.dob = dob;
        this.houseName = houseName;
        this.place = place;
        this.pincode = pincode;
        this.phone = phone;
        this.email = email;
        this.parentName = parentName;
        this.parentPhone = parentPhone;
    }
    public User(String firstName, String lastName, String course, String batch, String gender, String dob, String houseName, String place, String pincode, String phone, String email, String parentName, String parentPhone, Set passes, Set newPassengerRequests, Set payments, Set feedbacks, Set logins) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.course = course;
       this.batch = batch;
       this.gender = gender;
       this.dob = dob;
       this.houseName = houseName;
       this.place = place;
       this.pincode = pincode;
       this.phone = phone;
       this.email = email;
       this.parentName = parentName;
       this.parentPhone = parentPhone;
       this.passes = passes;
       this.newPassengerRequests = newPassengerRequests;
       this.payments = payments;
       this.feedbacks = feedbacks;
       this.logins = logins;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }
    public String getBatch() {
        return this.batch;
    }
    
    public void setBatch(String batch) {
        this.batch = batch;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public String getHouseName() {
        return this.houseName;
    }
    
    public void setHouseName(String houseName) {
        this.houseName = houseName;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    public String getPincode() {
        return this.pincode;
    }
    
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getParentName() {
        return this.parentName;
    }
    
    public void setParentName(String parentName) {
        this.parentName = parentName;
    }
    public String getParentPhone() {
        return this.parentPhone;
    }
    
    public void setParentPhone(String parentPhone) {
        this.parentPhone = parentPhone;
    }
    public Set getPasses() {
        return this.passes;
    }
    
    public void setPasses(Set passes) {
        this.passes = passes;
    }
    public Set getNewPassengerRequests() {
        return this.newPassengerRequests;
    }
    
    public void setNewPassengerRequests(Set newPassengerRequests) {
        this.newPassengerRequests = newPassengerRequests;
    }
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }
    public Set getFeedbacks() {
        return this.feedbacks;
    }
    
    public void setFeedbacks(Set feedbacks) {
        this.feedbacks = feedbacks;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }




}


